let
    // ══════════════════════════════════════════════════════════════
    // PF ECR CHALLAN EXTRACTOR
    // Extracts data from "COMBINED CHALLAN OF A/C NO. 01, 02, 10, 21 & 22"
    // (Employees' Provident Fund Organisation ECR Returns)
    // ══════════════════════════════════════════════════════════════

    // ── 1. READ FOLDER PATH FROM NAMED RANGE "Path_PF" ────────
    SourcePath = Excel.CurrentWorkbook(){[Name="Path_PF"]}[Content]{0}[Column1],

    // ── 2. GET ALL PDF FILES FROM FOLDER ─────────────────────────
    AllFiles   = Folder.Files(SourcePath),
    PDFsOnly   = Table.SelectRows(AllFiles, each Text.Lower([Extension]) = ".pdf"),
    FileCols   = Table.SelectColumns(PDFsOnly, {"Content", "Name"}),

    // ── 3. PARSE FUNCTION ────────────────────────────────────────
    fnParsePF = (bin as binary, fname as text) as record =>
    let
        ParsedRecord = try
        let
            // Load PDF Content
            RawData      = Pdf.Tables(bin, [Implementation="1.3"]),
            
            // For Tables (Numbers Extraction)
            TablesOnly   = Table.SelectRows(RawData, each [Kind] = "Table"),
            CombinedData = if Table.RowCount(TablesOnly) > 0 then Table.Combine(Table.Column(TablesOnly, "Data")) else #table({}, {}),
            AllRows      = Table.ToRows(CombinedData),

            // For Text (Header/Footer Information Extraction)
            AllPagesOrTables = if Table.RowCount(RawData) > 0 then Table.Combine(Table.Column(RawData, "Data")) else #table({}, {}),
            AllCellsText     = List.Transform(List.Combine(Table.ToRows(AllPagesOrTables)), (x) => try Text.Trim(Text.From(x)) otherwise ""),
            AllTextStr       = Text.Combine(List.Select(AllCellsText, each _ <> ""), " "),

            // ── HELPER: Safe text from any cell ──────────────────
            T = (v) => let s = try Text.Trim(Text.From(v)) otherwise "" in if s = null then "" else s,

            // ── HELPER: Clean and parse a number string ───────────
            N = (s as text) as nullable number =>
                 let c = Text.Trim(Text.Remove(s, {",", Character.FromNumber(160), Character.FromNumber(10), Character.FromNumber(13), "₹"}))
                 in if c = "" or c = "-" then 0 else try Number.FromText(c, "en-US") otherwise 0,

            // ── HELPER: Find all rows containing a label ──────────
            FindRows = (lbl as text) as list =>
                List.Select(AllRows, (r) => List.AnyTrue(List.Transform(r, (c) => Text.Contains(Text.Upper(T(c)), Text.Upper(lbl))))),

            // ── HELPER: Get numbers AFTER the label cell in a row ─
            GetNums = (r as list, lbl as text) as list =>
                let
                    texts  = List.Transform(r, T),
                    lblIdx = List.PositionOf(List.Transform(texts, each Text.Contains(Text.Upper(_), Text.Upper(lbl))), true),
                    after  = if lblIdx >= 0 then List.Range(texts, lblIdx + 1) else texts,
                    nums   = List.Select(List.Transform(after, N), each _ <> null),
                    padded = nums & {0,0,0,0,0,0,0,0,0,0}
                in padded,

            G = (lbl as text) as list =>
                let rows = FindRows(lbl) in if List.Count(rows) > 0 then GetNums(rows{0}, lbl) else {0,0,0,0,0,0,0,0,0,0},

            // ════════════════════════════════════════════════════════
            // STEP 1: BASIC IDENTIFIERS (Using Flattened Document Text)
            // ════════════════════════════════════════════════════════

            // ── Col 1 & 2: Establishment Code & Name ─────────────────────────
            idxEst = Text.PositionOf(AllTextStr, "Establishment Code & Name"),
            idxAddress = Text.PositionOf(AllTextStr, "Address"),
            EstSubStr = if idxEst >= 0 and idxAddress > idxEst then Text.Trim(Text.Middle(AllTextStr, idxEst + 25, idxAddress - (idxEst + 25))) else "",
            
            EstabCode = if EstSubStr <> "" then Text.Split(EstSubStr, " "){0} else "Unknown",
            EstabNameRaw = if EstSubStr <> "" then Text.Trim(Text.Replace(EstSubStr, EstabCode, "")) else "Unknown",
            
            // FIX 1: Trims out "Dues for the wage month" if it got pulled into the Name line
            EstabName = if Text.Contains(EstabNameRaw, "Dues for") then Text.Trim(Text.Split(EstabNameRaw, "Dues for"){0}) else EstabNameRaw,

            // ── Col 4: Month + Raw Year ───────────────────────────
            idxDues = Text.PositionOf(AllTextStr, "Dues for the wage month of"),
            MonthYearStr = if idxDues >= 0 then Text.Trim(Text.Middle(AllTextStr, idxDues + 26, 30)) else "",
            
            // FIX 2 & 3: Find the first digit to split Month and Year safely (solves "September2022" issue)
            FirstDigitIdx = Text.PositionOfAny(MonthYearStr, {"0","1","2","3","4","5","6","7","8","9"}),
            
            MonthVal = if FirstDigitIdx > 0 then Text.Trim(Text.Start(MonthYearStr, FirstDigitIdx)) 
                       else if MonthYearStr <> "" then Text.Split(MonthYearStr, " "){0} else "Unknown",
                       
            RawYearVal = if FirstDigitIdx >= 0 then 
                            try Number.FromText(Text.Start(Text.Select(Text.Middle(MonthYearStr, FirstDigitIdx), {"0","1","2","3","4","5","6","7","8","9"}), 4)) otherwise 0 
                         else 0,

            // ── Col 3: Financial Year (Dynamic calculation) ────────
            MonthUpper  = Text.Upper(MonthVal),
            IsQ1toQ3    = List.AnyTrue(List.Transform({"APR","MAY","JUN","JUL","AUG","SEP","OCT","NOV","DEC"}, each Text.Contains(MonthUpper, _))),
            FYStartYear = if RawYearVal = 0 then 0 else if IsQ1toQ3 then RawYearVal else RawYearVal - 1,
            FYEndYY     = if FYStartYear = 0 then "??" else Text.End(Text.From(FYStartYear + 1), 2),
            FinancialYear = if FYStartYear = 0 then "Unknown" else Text.From(FYStartYear) & "-" & FYEndYY,

            // ── Col 5: Challan Generation Date ────────────────────
            idxGen = Text.PositionOf(AllTextStr, "system generated challan on "),
            GenStr = if idxGen >= 0 then Text.Trim(Text.Middle(AllTextStr, idxGen + 28, 20)) else "",
            ChallanDate = if GenStr <> "" then Text.Split(GenStr, " "){0} else "Unknown",

            // ════════════════════════════════════════════════════════
            // STEP 2: TABLE DATA EXTRACTION
            // ════════════════════════════════════════════════════════
            rAdmin      = G("Administration Charges"),
            rEmployer   = G("Employer"),
            rEmployee   = G("Employee"),

            // ════════════════════════════════════════════════════════
            // STEP 3: CALCULATED COLUMNS
            // ════════════════════════════════════════════════════════
            Employer_EPF_AC01        = rEmployer{0},
            Employer_EPS_AC10        = rEmployer{2},
            Employer_EDLI_AC21       = rEmployer{3},
            Total_Employer           = Employer_EPF_AC01 + Employer_EPS_AC10 + Employer_EDLI_AC21,
            
            PF_Admin_AC02            = rAdmin{1},
            EDLI_Admin_AC22          = rAdmin{4},
            Total_Admin              = PF_Admin_AC02 + EDLI_Admin_AC22,
            
            Total_Employer_wAdmin    = Total_Employer + Total_Admin,
            Employee_EPF_AC01        = rEmployee{0},
            Grand_Total              = Total_Employer_wAdmin + Employee_EPF_AC01

        in
            [
                #"Establishment_Code"            = EstabCode,
                #"Establishment_Name"            = EstabName,
                #"Financial_Year"                = FinancialYear,
                #"Month"                         = MonthVal,
                #"Challan_Date"                  = ChallanDate,
                
                #"Employer_EPF_AC01"             = Employer_EPF_AC01,
                #"Employer_EPS_AC10"             = Employer_EPS_AC10,
                #"Employer_EDLI_AC21"            = Employer_EDLI_AC21,
                #"Total_Employer_Contribution"   = Total_Employer,
                
                #"PF_Admin_AC02"                 = PF_Admin_AC02,
                #"EDLI_Admin_AC22"               = EDLI_Admin_AC22,
                #"Total_Admin_Charges"           = Total_Admin,
                
                #"Total_Employer_incl_Admin"     = Total_Employer_wAdmin,
                #"Employee_EPF_AC01"             = Employee_EPF_AC01,
                #"Grand_Total"                   = Grand_Total
            ]

        // Error fallback
        otherwise
            [
                #"Establishment_Code"            = "PARSE ERROR",
                #"Establishment_Name"            = "ERROR",
                #"Financial_Year"                = "ERROR",
                #"Month"                         = fname,
                #"Challan_Date"                  = "ERROR",
                #"Employer_EPF_AC01"             = null,
                #"Employer_EPS_AC10"             = null,
                #"Employer_EDLI_AC21"            = null,
                #"Total_Employer_Contribution"   = null,
                #"PF_Admin_AC02"                 = null,
                #"EDLI_Admin_AC22"               = null,
                #"Total_Admin_Charges"           = null,
                #"Total_Employer_incl_Admin"     = null,
                #"Employee_EPF_AC01"             = null,
                #"Grand_Total"                   = null
            ]
    in
        ParsedRecord,

    // ── 4. APPLY PARSER TO EVERY PDF ─────────────────────────────
    ParsedTable  = Table.AddColumn(FileCols, "ExtractedData", each fnParsePF([Content], [Name])),
    RemovedFiles = Table.RemoveColumns(ParsedTable, {"Content", "Name"}),

    // ── 5. EXPAND ALL 15 COLUMNS ─────────────────────────────────
    ExpandedData = Table.ExpandRecordColumn(RemovedFiles, "ExtractedData", {
        "Establishment_Code", "Establishment_Name", "Financial_Year", "Month", "Challan_Date",
        "Employer_EPF_AC01", "Employer_EPS_AC10", "Employer_EDLI_AC21", "Total_Employer_Contribution",
        "PF_Admin_AC02", "EDLI_Admin_AC22", "Total_Admin_Charges", "Total_Employer_incl_Admin",
        "Employee_EPF_AC01", "Grand_Total"
    }),

    // ── 6. SET DATA TYPES ────────────────────────────────────────
    TypedData = Table.TransformColumnTypes(ExpandedData, {
        {"Establishment_Code",          type text},
        {"Establishment_Name",          type text},
        {"Financial_Year",              type text},
        {"Month",                       type text},
        {"Challan_Date",                type text},
        {"Employer_EPF_AC01",           type number},
        {"Employer_EPS_AC10",           type number},
        {"Employer_EDLI_AC21",          type number},
        {"Total_Employer_Contribution", type number},
        {"PF_Admin_AC02",               type number},
        {"EDLI_Admin_AC22",             type number},
        {"Total_Admin_Charges",         type number},
        {"Total_Employer_incl_Admin",   type number},
        {"Employee_EPF_AC01",           type number},
        {"Grand_Total",                 type number}
    }),

    // ── 7. ADD MONTH INDEX FOR FINANCIAL YEAR SORTING ────────────
    AddMonthIndex = Table.AddColumn(TypedData, "MonthIndex", each
        let m = Text.Upper(try [Month] otherwise "")
        in
            if Text.Contains(m, "APR") then 1
            else if Text.Contains(m, "MAY") then 2
            else if Text.Contains(m, "JUN") then 3
            else if Text.Contains(m, "JUL") then 4
            else if Text.Contains(m, "AUG") then 5
            else if Text.Contains(m, "SEP") then 6
            else if Text.Contains(m, "OCT") then 7
            else if Text.Contains(m, "NOV") then 8
            else if Text.Contains(m, "DEC") then 9
            else if Text.Contains(m, "JAN") then 10
            else if Text.Contains(m, "FEB") then 11
            else if Text.Contains(m, "MAR") then 12
            else 99
    ),

    // ── 8. SORT: Financial Year → Month (FY order) → Estab Code ──
    SortedData = Table.Sort(AddMonthIndex, {
        {"Financial_Year",      Order.Ascending},
        {"MonthIndex",          Order.Ascending},
        {"Establishment_Code",  Order.Ascending}
    }),

    // ── 9. REMOVE HELPER COLUMN ───────────────────────────────────
    FinalData = Table.RemoveColumns(SortedData, {"MonthIndex"})
in
    FinalData