let
    // ══════════════════════════════════════════════════════════════
    // TDS ITNS 281 CHALLAN EXTRACTOR — SEQUENCE ARRAY METHOD
    // ══════════════════════════════════════════════════════════════

    // ── 1. READ FOLDER PATH ───────────────────────────────────────
    SourcePath = Excel.CurrentWorkbook(){[Name="Path_TDS"]}[Content]{0}[Column1],

    // ── 2. GET ALL PDF FILES FROM FOLDER ─────────────────────────
    AllFiles = Folder.Files(SourcePath),
    PDFsOnly = Table.SelectRows(AllFiles, each Text.Lower([Extension]) = ".pdf"),
    FileCols = Table.SelectColumns(PDFsOnly, {"Content", "Name"}),

    // ── 3. PARSE FUNCTION ────────────────────────────────────────
    fnParseTDS = (bin as binary, fname as text) as record =>
    let
        ParsedRecord = try
        let
            // Load all content from PDF
            RawData = Pdf.Tables(bin, [Implementation="1.3"]),
            AllContent = if Table.RowCount(RawData) > 0 then Table.Combine(Table.Column(RawData, "Data")) else #table({}, {}),
            
            // ── FLATTEN & CLEAN SEQUENCE ──
            FlatList = List.Transform(List.Combine(Table.ToRows(AllContent)), (x) => try Text.Trim(Text.From(x)) otherwise ""),
            CleanCellsOrig = List.Select(List.Transform(FlatList, each Text.Trim(Text.Remove(_, {":"}))), each _ <> "" and _ <> null),
            CleanCellsUpper = List.Transform(CleanCellsOrig, Text.Upper),

            // ══════════════════════════════════════════════════════
            // HELPER FUNCTIONS
            // ══════════════════════════════════════════════════════

            FindIdx = (lbl as text) => List.PositionOf(CleanCellsUpper, Text.Upper(lbl)),

            FindVal = (lbl as text) =>
                let idx = FindIdx(lbl)
                in if idx >= 0 and idx + 1 < List.Count(CleanCellsOrig) then CleanCellsOrig{idx + 1} else "",

            FindValBetween = (lbl1 as text, lbl2 as text) =>
                let
                    idx1 = FindIdx(lbl1),
                    idx2 = FindIdx(lbl2)
                in
                    if idx1 >= 0 and idx2 > idx1 then
                        Text.Combine(List.Range(CleanCellsOrig, idx1 + 1, idx2 - idx1 - 1), " ")
                    else FindVal(lbl1),

            N = (s as text) =>
                let
                    chars = Text.ToList(s),
                    validChars = List.Select(chars, each List.Contains({"0".."9", "-"}, _)),
                    str = Text.Combine(validChars),
                    val = if str = "" or str = "-" then 0 else try Number.FromText(str) otherwise 0
                in val,

            // ══════════════════════════════════════════════════════
            // STEP 1: EXTRACTION
            // ══════════════════════════════════════════════════════

            TAN_Val       = FindVal("TAN"),
            
            // Isolate Name and strip out "Assessment Year"
            CompanyNameRaw = FindValBetween("NAME", "FINANCIAL YEAR"),
            idxAss = Text.PositionOf(Text.Upper(CompanyNameRaw), "ASSESSMENT YEAR"),
            CompanyName = if idxAss >= 0 then Text.Trim(Text.Start(CompanyNameRaw, idxAss)) else CompanyNameRaw,

            FY_Val        = FindVal("FINANCIAL YEAR"),
            
            NOP_Raw       = FindVal("NATURE OF PAYMENT"),
            Section_Val   = if NOP_Raw <> "" then Text.Split(NOP_Raw, " "){0} else "Unknown",

            // ── UPDATED: MAJOR HEAD LOGIC ──
            // Checks for specific keywords and strictly outputs either "Other than Companies" or "Corporation Tax"
            MajorHeadRaw  = FindVal("MAJOR HEAD"),
            MH_Upper      = Text.Upper(MajorHeadRaw),
            MajorHead_Val = if Text.Contains(MH_Upper, "OTHER THAN COMPAN") or Text.Contains(MH_Upper, "0021") then "Other than Companies"
                            else if Text.Contains(MH_Upper, "COMPAN") or Text.Contains(MH_Upper, "CORPORATION") or Text.Contains(MH_Upper, "0020") then "Corporation Tax"
                            else Text.Trim(Text.Split(MajorHeadRaw, "("){0}), // Fallback: trims out brackets

            ChallanNo_Val = FindVal("CHALLAN NO"),
            
            PDateStr      = FindVal("DATE OF DEPOSIT"),
            PaymentDate   = try Date.FromText(PDateStr, [Culture="en-IN"]) otherwise (try Date.FromText(PDateStr, [Culture="en-US"]) otherwise null),

            TotalAmountPaid = N(FindVal("AMOUNT (IN RS.)")),
            
            // ── TAX BREAKUP ──
            Tax           = N(FindVal("TAX")),
            Surcharge     = N(FindVal("SURCHARGE")),
            Cess          = N(FindVal("CESS")),
            InterestAmt   = N(FindVal("INTEREST")),
            Penalty       = N(FindVal("PENALTY")),
            Fee234E       = N(FindVal("FEE UNDER SECTION 234E")),

            CrosscheckDiff = TotalAmountPaid - (Tax + Surcharge + Cess + InterestAmt + Penalty + Fee234E),

            // ── TDS MONTH LOGIC ──
            TDS_Month =
                if PaymentDate = null then "Unknown"
                else
                    let
                        PDay = Date.Day(PaymentDate),
                        PMonth = Date.Month(PaymentDate),
                        PYear = Date.Year(PaymentDate),

                        DeductionDate =
                            if PMonth = 4 then #date(PYear, 3, 1) 
                            else if PDay <= 7 then Date.AddMonths(#date(PYear, PMonth, 1), -1) 
                            else if InterestAmt > 0 then Date.AddMonths(#date(PYear, PMonth, 1), -1) 
                            else #date(PYear, PMonth, 1), 
                            
                        MonthName = Date.MonthName(DeductionDate),
                        YearName = Text.From(Date.Year(DeductionDate))
                    in MonthName & " " & YearName

        in
            [
                #"TAN"                    = if TAN_Val = "" then "Unknown" else TAN_Val,
                #"Company Name"           = CompanyName,
                #"FY"                     = FY_Val,
                #"Month"                  = TDS_Month,
                #"Section"                = Section_Val,
                #"Major Head"             = MajorHead_Val,
                #"Total Amount Paid"      = TotalAmountPaid,
                #"Tax"                    = Tax,
                #"Surcharge"              = Surcharge,
                #"Cess"                   = Cess,
                #"Interest"               = InterestAmt,
                #"Penalty"                = Penalty,
                #"Fee under section 234E" = Fee234E,
                #"Crosscheck Diff"        = CrosscheckDiff,
                #"Challan No"             = ChallanNo_Val,
                #"Payment Date"           = PaymentDate
            ]

        otherwise
            [
                #"TAN" = "ERROR", #"Company Name" = fname, #"FY" = null, #"Month" = null, 
                #"Section" = null, #"Major Head" = null, #"Total Amount Paid" = null, 
                #"Tax" = null, #"Surcharge" = null, #"Cess" = null, #"Interest" = null, 
                #"Penalty" = null, #"Fee under section 234E" = null, #"Crosscheck Diff" = null, 
                #"Challan No" = null, #"Payment Date" = null
            ]
    in
        ParsedRecord,

    // ── 4. APPLY PARSER TO EVERY PDF ─────────────────────────────
    ParsedTable  = Table.AddColumn(FileCols, "ExtractedData", each fnParseTDS([Content], [Name])),
    RemovedFiles = Table.RemoveColumns(ParsedTable, {"Content", "Name"}),

    // ── 5. EXPAND ALL 16 COLUMNS ─────────────────────────────────
    ExpandedData = Table.ExpandRecordColumn(RemovedFiles, "ExtractedData", {
        "TAN", "Company Name", "FY", "Month", "Section", "Major Head", "Total Amount Paid",
        "Tax", "Surcharge", "Cess", "Interest", "Penalty", "Fee under section 234E",
        "Crosscheck Diff", "Challan No", "Payment Date"
    }),

    // ── 6. SET DATA TYPES ────────────────────────────────────────
    TypedData = Table.TransformColumnTypes(ExpandedData, {
        {"TAN", type text}, {"Company Name", type text}, {"FY", type text}, {"Month", type text}, 
        {"Section", type text}, {"Major Head", type text}, {"Total Amount Paid", type number}, 
        {"Tax", type number}, {"Surcharge", type number}, {"Cess", type number}, 
        {"Interest", type number}, {"Penalty", type number}, {"Fee under section 234E", type number}, 
        {"Crosscheck Diff", type number}, {"Challan No", type text}, {"Payment Date", type date}
    }),

    // ── 7. ADD MONTH INDEX FOR SORTING ───────────────────────────
    AddMonthIdx = Table.AddColumn(TypedData, "_MonthIdx", each
        let m = if [Month] = null then "" else Text.Upper([Month]) in
            if Text.Contains(m, "APR") then 1 else if Text.Contains(m, "MAY") then 2
            else if Text.Contains(m, "JUN") then 3 else if Text.Contains(m, "JUL") then 4
            else if Text.Contains(m, "AUG") then 5 else if Text.Contains(m, "SEP") then 6
            else if Text.Contains(m, "OCT") then 7 else if Text.Contains(m, "NOV") then 8
            else if Text.Contains(m, "DEC") then 9 else if Text.Contains(m, "JAN") then 10
            else if Text.Contains(m, "FEB") then 11 else if Text.Contains(m, "MAR") then 12 else 99
    ),

    // ── 8. SORT BY MONTH, THEN SECTION ───────────────────────────
    SortedData = Table.Sort(AddMonthIdx, {
        {"_MonthIdx", Order.Ascending}, 
        {"Section", Order.Ascending}, 
        {"TAN", Order.Ascending}
    }),
    
    // ── 9. CLEAN UP HELPER COLUMN ────────────────────────────────
    FinalData  = Table.RemoveColumns(SortedData, {"_MonthIdx"})

in
    FinalData