let
    // ══════════════════════════════════════════════════════════════
    // ESIC CHALLAN EXTRACTOR & CONSOLIDATOR
    // Extracts data, groups Employer/Employee Challans by Month,
    // and handles missing files with clean blanks instead of nulls.
    // ══════════════════════════════════════════════════════════════

    // ── 1. READ FOLDER PATH FROM NAMED RANGE "Path_ESIC" ────────
    SourcePath = Excel.CurrentWorkbook(){[Name="Path_ESIC"]}[Content]{0}[Column1],

    // ── 2. GET ALL PDF FILES FROM FOLDER ─────────────────────────
    AllFiles   = Folder.Files(SourcePath),
    PDFsOnly   = Table.SelectRows(AllFiles, each Text.Lower([Extension]) = ".pdf"),
    FileCols   = Table.SelectColumns(PDFsOnly, {"Content", "Name"}),

    // ── 3. PARSE FUNCTION ────────────────────────────────────────
    fnParseESIC = (bin as binary, fname as text) as record =>
    let
        ParsedRecord = try
        let
            RawData      = Pdf.Tables(bin, [Implementation="1.3"]),
            AllPagesOrTables = if Table.RowCount(RawData) > 0 then Table.Combine(Table.Column(RawData, "Data")) else #table({}, {}),
            AllCellsText     = List.Transform(List.Combine(Table.ToRows(AllPagesOrTables)), (x) => try Text.Trim(Text.From(x)) otherwise ""),
            AllTextStr       = Text.Combine(List.Select(AllCellsText, each _ <> ""), " "),

            // Challan Period (Month & Year)
            idxPeriod = Text.PositionOf(AllTextStr, "Challan Period:"),
            PeriodStrRaw = if idxPeriod >= 0 then Text.Trim(Text.Middle(AllTextStr, idxPeriod + 15, 20)) else "",
            PeriodStr = if PeriodStrRaw <> "" then Text.Split(PeriodStrRaw, " "){0} else "", 
            
            MonthVal = if Text.Contains(PeriodStr, "-") then Text.Split(PeriodStr, "-"){0} else "Unknown",
            RawYearVal = if Text.Contains(PeriodStr, "-") then try Number.FromText(Text.Split(PeriodStr, "-"){1}) otherwise 0 else 0,

            // Financial Year Calculation
            MonthUpper  = Text.Upper(MonthVal),
            IsQ1toQ3    = List.AnyTrue(List.Transform({"APR","MAY","JUN","JUL","AUG","SEP","OCT","NOV","DEC"}, each Text.Contains(MonthUpper, _))),
            FYStartYear = if RawYearVal = 0 then 0 else if IsQ1toQ3 then RawYearVal else RawYearVal - 1,
            FYEndYY     = if FYStartYear = 0 then "??" else Text.End(Text.From(FYStartYear + 1), 2),
            FinancialYear = if FYStartYear = 0 then "Unknown" else Text.From(FYStartYear) & "-" & FYEndYY,

            // Amount Paid
            idxAmount = Text.PositionOf(AllTextStr, "Amount Paid:"),
            AmountStrRaw = if idxAmount >= 0 then Text.Trim(Text.Middle(AllTextStr, idxAmount + 12, 20)) else "",
            AmountPaidStr = if AmountStrRaw <> "" then Text.Split(AmountStrRaw, " "){0} else "0",
            AmountPaidVal = try Number.FromText(AmountPaidStr) otherwise 0,

            // Challan Number 
            idxChallan = Text.PositionOf(AllTextStr, "Challan Number"),
            ChallanNumRaw = if idxChallan >= 0 then Text.Trim(Text.Middle(AllTextStr, idxChallan + 14, 30)) else "",
            ChallanCleaned = Text.Trim(Text.Replace(ChallanNumRaw, ":", "")),
            ChallanNum = if ChallanCleaned <> "" then Text.Split(ChallanCleaned, " "){0} else "Unknown",

            // Challan Submitted Date
            idxDate = Text.PositionOf(AllTextStr, "Challan Submitted Date"),
            DateStrRaw = if idxDate >= 0 then Text.Trim(Text.Middle(AllTextStr, idxDate + 22, 30)) else "",
            DateStr = if DateStrRaw <> "" then Text.Split(DateStrRaw, " "){0} else "Unknown"

        in
            [
                #"Month"                        = MonthVal,
                #"Year"                         = FinancialYear,
                #"Total ESIC Contribution Paid" = AmountPaidVal,
                #"Challan Number"               = ChallanNum,
                #"Date of Payment"              = DateStr
            ]
        otherwise
            [
                #"Month"                        = fname,
                #"Year"                         = "ERROR",
                #"Total ESIC Contribution Paid" = 0,
                #"Challan Number"               = "ERROR",
                #"Date of Payment"              = "ERROR"
            ]
    in
        ParsedRecord,

    // ── 4. APPLY PARSER TO EVERY PDF ─────────────────────────────
    ParsedTable  = Table.AddColumn(FileCols, "ExtractedData", each fnParseESIC([Content], [Name])),
    RemovedFiles = Table.RemoveColumns(ParsedTable, {"Content", "Name"}),

    // ── 5. EXPAND RAW COLUMNS ────────────────────────────────────
    ExpandedData = Table.ExpandRecordColumn(RemovedFiles, "ExtractedData", {
        "Month", "Year", "Total ESIC Contribution Paid", "Challan Number", "Date of Payment"
    }),

    // ── 6. GROUP AND SPLIT LOGIC (EMPLOYER VS EMPLOYEE) ──────────
    GroupedByMonth = Table.Group(ExpandedData, {"Year", "Month"}, {
        {"AllData", each _, type table [Month=nullable text, Year=nullable text, Total ESIC Contribution Paid=nullable number, Challan Number=nullable text, Date of Payment=nullable text]}
    }),

    ProcessedGroups = Table.AddColumn(GroupedByMonth, "ConsolidatedRecords", each 
        let
            SortedTable = Table.Sort([AllData],{{"Total ESIC Contribution Paid", Order.Descending}}),
            RowCount = Table.RowCount(SortedTable),
            
            EmployerRecord = if RowCount > 0 then SortedTable{0} else null,
            EmployeeRecord = if RowCount > 1 then SortedTable{1} else null,
            
            EmpAmount = if EmployerRecord <> null then EmployerRecord[Total ESIC Contribution Paid] else 0,
            EeAmount  = if EmployeeRecord <> null then EmployeeRecord[Total ESIC Contribution Paid] else 0,
            
            // Replaced 'null' with '""' to keep fields clean when data is missing
            EmpChallan = if EmployerRecord <> null then EmployerRecord[Challan Number] else "",
            EeChallan  = if EmployeeRecord <> null then EmployeeRecord[Challan Number] else "",
            
            EmpDate = if EmployerRecord <> null then EmployerRecord[Date of Payment] else "",
            EeDate  = if EmployeeRecord <> null then EmployeeRecord[Date of Payment] else "",
            
            TotalVal = EmpAmount + EeAmount
        in
            [
                #"Employer ESIC Contribution"           = EmpAmount,
                #"Employee ESIC Contribution"           = EeAmount,
                #"Employer Contribution Challan Number" = EmpChallan,
                #"Employee Contribution Challan Number" = EeChallan,
                #"Employer Contribution Challan Date"   = EmpDate,
                #"Employee Contribution Challan Date"   = EeDate,
                #"Total ESIC Contribution"              = TotalVal
            ]
    ),

    // ── 7. EXPAND FINAL COLUMNS ──────────────────────────────────
    FinalExpanded = Table.ExpandRecordColumn(ProcessedGroups, "ConsolidatedRecords", {
        "Employer ESIC Contribution", "Employee ESIC Contribution", 
        "Employer Contribution Challan Number", "Employee Contribution Challan Number", 
        "Employer Contribution Challan Date", "Employee Contribution Challan Date", 
        "Total ESIC Contribution"
    }),

    CleanedColumns = Table.RemoveColumns(FinalExpanded,{"AllData"}),

    // ── 8. SET DATA TYPES ────────────────────────────────────────
    TypedData = Table.TransformColumnTypes(CleanedColumns, {
        {"Month",                                type text},
        {"Year",                                 type text},
        {"Employer ESIC Contribution",           type number},
        {"Employee ESIC Contribution",           type number},
        {"Employer Contribution Challan Number", type text},
        {"Employee Contribution Challan Number", type text},
        {"Employer Contribution Challan Date",   type text},
        {"Employee Contribution Challan Date",   type text},
        {"Total ESIC Contribution",              type number}
    }),

    // ── 9. ADD MONTH INDEX FOR FINANCIAL YEAR SORTING ────────────
    AddMonthIndex = Table.AddColumn(TypedData, "MonthIndex", each
        let m = Text.Upper(try [Month] otherwise "")
        in
            if Text.Contains(m, "APR") then 1
            else if Text.Contains(m, "MAY") then 2
            else if Text.Contains(m, "JUN") then 3
            else if Text.Contains(m, "JUL") then 4
            else if Text.Contains(m, "AUG") then 5
            else if Text.Contains(m, "SEP") then 6
            else if Text.Contains(m, "OCT") then 7
            else if Text.Contains(m, "NOV") then 8
            else if Text.Contains(m, "DEC") then 9
            else if Text.Contains(m, "JAN") then 10
            else if Text.Contains(m, "FEB") then 11
            else if Text.Contains(m, "MAR") then 12
            else 99
    ),

    // ── 10. FINAL CHRONOLOGICAL SORT ─────────────────────────────
    SortedData = Table.Sort(AddMonthIndex, {
        {"Year",       Order.Ascending},
        {"MonthIndex", Order.Ascending}
    }),

    // ── 11. REMOVE HELPER INDEX ──────────────────────────────────
    FinalData = Table.RemoveColumns(SortedData, {"MonthIndex"})
in
    FinalData